[project]
name = "discord-bot-orm-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.16.4",
    "disnake>=2.10.1",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.41",
]
