"""Create tables

Revision ID: 97f9f899f1f4
Revises: 
Create Date: 2025-07-25 20:26:39.890764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f9f899f1f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=200), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('result_text', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('reports_admins',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_index(op.f('ix_reports_admins_id'), 'reports_admins', ['id'], unique=False)
    op.create_table('reports_configs',
    sa.Column('is_reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_logs_enabled', sa.Boolean(), nullable=False),
    sa.Column('logs_channel_id', sa.Integer(), nullable=True),
    sa.Column('report_tickets_category_id', sa.Integer(), nullable=True),
    sa.Column('enabled_logs_types', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_reports_configs_id'), 'reports_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_configs_id'), table_name='reports_configs')
    op.drop_table('reports_configs')
    op.drop_index(op.f('ix_reports_admins_id'), table_name='reports_admins')
    op.drop_table('reports_admins')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
